database:
  driver: "mysql"
  dbname: "len"
  username: "root"
  password: ""
  host: "127.0.0.1"
  port: "3306"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

server:
  port: "5000"
  #release | debug
  mode: "debug"